### ISSUE TITLE
Misleading tqdm progress with num_styles greater than 1

### ISSUE THREAD

**Issue by nik123** [Hvitgar/stylize-datasets#10]
I have dataset of 3999 images and I want to stylize it with num-styles=5. When stylize.py script will successfully finish it's work the progress would be at 20% mark. Here is example of the output:

```
20%|███████████▊                                               | 3999/19995
```

The problem is in line 116 in stylize.py: ` with tqdm(total=len(content_paths) * args.num_styles) as pbar`. The `pbar` is created with len of number of images multiplied by number of styles. However `pbar` is updated only num_images times (line 156). The `pbar` object should be either of length of `content_paths` either should be updated after every style is applied.

**Comment by bmitzkus** [comment]
Nice catch! Gonna update `pbar` in every iteration.
