### ISSUE TITLE
Any idea for data parrel?

### ISSUE THREAD

**Issue by jacob-kang** [Hvitgar/stylize-datasets#21]
Hello, thanks for your great work.

I'm making stylized-coco.
But due to CUDA out of memory, Some images (Actually 2 out of 3) are skipped.

I use Gtx 1080 ti x 5.

Do you know how to handle this code parallel?

Thanks.

**Comment by bmitzkus** [comment]
have you looked into the --style-size option? It is set to 512 on default, decreasing it to 256 or 128 might help with your memory problem.

**Comment by jacob-kang** [comment]
> have you looked into the --style-size option? It is set to 512 on default, decreasing it to 256 or 128 might help with your memory problem.

I'm sorry. I should've added that.
To maintain bbox, I use --sylize-size as 0.
I want to preserve the images as the state like normal COCO dataset.

**Comment by bmitzkus** [comment]
but the style size shouldn't interfere with your bboxes - it just downscales the images used for stylization, the resulting stylized images will have the dimensions of the input if you set --content-size to 0.

**Comment by jacob-kang** [comment]
> but the style size shouldn't interfere with your bboxes - it just downscales the images used for stylization, the resulting stylized images will have the dimensions of the input if you set --content-size to 0.

Oh ohohoh my goodness!
My bad.
Thanks for your kind help.

Cheers!
