### ISSUE TITLE
too many style images

### ISSUE THREAD

**Issue by njustymk** [Hvitgar/stylize-datasets#6]
There are too many style images train.zip is 36GB, Do I have to download all?

**Comment by njustymk** [comment]
i have got it , thank you!

**Comment by RamatovInomjon** [comment]
> i have got it , thank you!
Hi, 
Should we download all?

**Comment by bmitzkus** [comment]
You can use any images you like as style images. Usage of the painter-by-numbers dataset is just a suggestion. Of course you can just download and use a subset of that dataset, any number of style images will work
