### ISSUE TITLE
stylizing the datasets

### ISSUE THREAD

**Issue by GhanimAlSuwaidi** [Hvitgar/stylize-datasets#9]
what format should the datasets be when applied into the content directory? and in what format are they transformed to?

**Comment by bmitzkus** [comment]
I assume you are talking about image file types? In that case, you can specify the extensions the script is looking for in the content directory via `--extensions <EX0> <EX1> ...`, so if your images are jpg, set `--extensions jpg`.

Images will be stored in the exact same file type they were found in. jpg stays jpg, png stays png and so on.

**Comment by GhanimAlSuwaidi** [comment]
I'm trying to use this on STL10, and CIFAR10. 
I have the datasets as binary files, and id love to use them in that format. is it possible to keep them in that format?

**Comment by bmitzkus** [comment]
are you using some sort of pytorch dataloader? I think it should be straight forward to implement a wrapper around the `stylize()` such that it can be used as a `torchvision.transforms` transform directly in the data preprocessing step (at some point, your binary needs to be converted to a tensor, right?)
